export let pieces = [
  // Black Pieces
  {
    id: "WK1",
    name: "K",
    color: "black",
    number: 1,
    movesArray: [],
    position: { column: "E", row: 1 },
  },
  {
    id: "WQ1",
    name: "Q",
    color: "black",
    number: 1,
    movesArray: [],
    position: { column: "D", row: 1 },
  },
  {
    id: "WR1",
    name: "R",
    color: "black",
    number: 1,
    movesArray: [],
    position: { column: "A", row: 1 },
  },
  {
    id: "WR2",
    name: "R",
    color: "black",
    number: 2,
    movesArray: [],
    position: { column: "H", row: 1 },
  },
  {
    id: "WN1",
    name: "N",
    color: "black",
    number: 1,
    movesArray: [],
    position: { column: "B", row: 1 },
  },
  {
    id: "WN2",
    name: "N",
    color: "black",
    number: 2,
    movesArray: [],
    position: { column: "G", row: 1 },
  },
  {
    id: "WB1",
    name: "B",
    color: "black",
    number: 1,
    movesArray: [],
    position: { column: "C", row: 1 },
  },
  {
    id: "WB2",
    name: "B",
    color: "black",
    number: 2,
    movesArray: [],
    position: { column: "F", row: 1 },
  },
  {
    id: "WP1",
    name: "P",
    color: "black",
    number: 1,
    movesArray: [],
    position: { column: "A", row: 2 },
  },
  {
    id: "WP2",
    name: "P",
    color: "black",
    number: 2,
    movesArray: [],
    position: { column: "B", row: 2 },
  },

  // White Pieces
  {
    id: "BK1",
    name: "K",
    color: "white",
    number: 1,
    movesArray: [],
    position: { column: "E", row: 8 },
  },
  {
    id: "BQ1",
    name: "Q",
    color: "white",
    number: 1,
    movesArray: [],
    position: { column: "D", row: 8 },
  },
  {
    id: "BR1",
    name: "R",
    color: "white",
    number: 1,
    movesArray: [],
    position: { column: "A", row: 8 },
  },
  {
    id: "BR2",
    name: "R",
    color: "white",
    number: 2,
    movesArray: [],
    position: { column: "H", row: 8 },
  },
  {
    id: "BN1",
    name: "N",
    color: "white",
    number: 1,
    movesArray: [],
    position: { column: "B", row: 8 },
  },
  {
    id: "BN2",
    name: "N",
    color: "white",
    number: 2,
    movesArray: [],
    position: { column: "G", row: 8 },
  },
  {
    id: "BB1",
    name: "B",
    color: "white",
    number: 1,
    movesArray: [],
    position: { column: "C", row: 8 },
  },
  {
    id: "BB2",
    name: "B",
    color: "white",
    number: 2,
    movesArray: [],
    position: { column: "F", row: 8 },
  },
  {
    id: "BP1",
    name: "P",
    color: "white",
    number: 1,
    movesArray: [],
    position: { column: "A", row: 7 },
  },
  {
    id: "BP2",
    name: "P",
    color: "white",
    number: 2,
    movesArray: [],
    position: { column: "B", row: 7 },
  },
  {
    id: "BP3",
    name: "P",
    color: "white",
    number: 3,
    movesArray: [],
    position: { column: "C", row: 7 },
  },
  {
    id: "BP4",
    name: "P",
    color: "white",
    number: 4,
    movesArray: [],
    position: { column: "D", row: 7 },
  },
  {
    id: "BP5",
    name: "P",
    color: "white",
    number: 5,
    movesArray: [],
    position: { column: "E", row: 7 },
  },
  {
    id: "BP6",
    name: "P",
    color: "white",
    number: 6,
    movesArray: [],
    position: { column: "F", row: 7 },
  },
  {
    id: "BP7",
    name: "P",
    color: "white",
    number: 7,
    movesArray: [],
    position: { column: "G", row: 7 },
  },
  {
    id: "BP8",
    name: "P",
    color: "white",
    number: 8,
    movesArray: [],
    position: { column: "H", row: 7 },
  }
  //Add more pieces as needed...
];
